export const INVENTORY_ACTIONS = {
  SET_PRODUCTS: "SET_PRODUCTS",

  SET_SEARCH: "SET_SEARCH",
  SET_STATUS: "SET_STATUS",
  SET_CATEGORY: "SET_CATEGORY",
  SET_WAREHOUSE: "SET_WAREHOUSE",
  SET_SORT: "SET_SORT",

  SET_PAGE: "SET_PAGE",
  SET_PAGE_SIZE: "SET_PAGE_SIZE",

  SET_SELECTED_PRODUCT: "SET_SELECTED_PRODUCT",

  OPEN_MODAL: "OPEN_MODAL",
  CLOSE_MODAL: "CLOSE_MODAL",

  SET_LOADING: "SET_LOADING",
  SET_ERROR: "SET_ERROR",

  ADD_PRODUCT: "ADD_PRODUCT",
  UPDATE_PRODUCT: "UPDATE_PRODUCT",
  DELETE_PRODUCT: "DELETE_PRODUCT",
  UPDATE_STOCK: "UPDATE_STOCK",
};