export const INVENTORY_ACTIONS = {

  SET_PRODUCTS: "SET_PRODUCTS",

  ADD_PRODUCT: "ADD_PRODUCT",

  UPDATE_PRODUCT: "UPDATE_PRODUCT",

  DELETE_PRODUCT: "DELETE_PRODUCT",

  RESTOCK_PRODUCT: "RESTOCK_PRODUCT",

  SET_SEARCH: "SET_SEARCH",

  SET_STATUS: "SET_STATUS",

  SET_CATEGORY: "SET_CATEGORY",

  SET_WAREHOUSE: "SET_WAREHOUSE",

  SET_SORT: "SET_SORT",

  SET_PAGE: "SET_PAGE",

  OPEN_MODAL: "OPEN_MODAL",

  CLOSE_MODAL: "CLOSE_MODAL",

  SET_SELECTED_PRODUCT: "SET_SELECTED_PRODUCT",
  UPDATE_PRODUCT: "UPDATE_PRODUCT",

DELETE_PRODUCT: "DELETE_PRODUCT",

UPDATE_STOCK: "UPDATE_STOCK",

};